apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    release: prom
    role: alert-rules
  name: prometheus-rules
spec:
  groups: []
  # - name: SLOs-http_requests_total
  #   rules:
  #   - alert: ErrorBudgetBurn
  #     annotations:
  #       message: 'High error budget burn for job=prometheus (current value: {{ $value }})'
  #     expr: |
  #       sum(http_requests_total:burnrate5m{job="prometheus"}) > (14.40 * (1-0.99900))
  #       and
  #       sum(http_requests_total:burnrate1h{job="prometheus"}) > (14.40 * (1-0.99900))
  #     for: 2m
  #     labels:
  #       job: prometheus
  #       severity: critical
