apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spellbook-service-monitor
  namespace: team-epimetheus
  labels:
    app: spellbook
    release: prom
spec:
  selector:
    matchLabels:
      app: spellbook
  namespaceSelector:
    matchNames:
    - team-epimetheus
  endpoints:
   - path: /actuator/prometheus
     interval: 15s
     port: http
