apiVersion: v1
kind: Service
metadata:
  name: spellbook-service
  namespace: team-epimetheus
  labels:
    app: spellbook
spec:
  type: ClusterIP
  selector:
    app: spellbook
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http