apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  endpoints:
  - interval: 15s
    path: /actuator/prometheus
    port: http
  serviceAccountName: prometheus
  namespaceSelector:
    matchNames:
    - team-epimetheus
  selector:
    matchLabels:
      app: spellbook
